const products = [
    {
        id: '1',
        name: 'All 10 in 1 Signature Pack',
        category: 'Combo Packs',
        sweetener: 'Jaggery',
        price: 649,
        originalPrice: 699,
        rating: 4.8,
        reviews: 12,
        image: 'images/p1.jpg',
        badge: 'Save 7%',
        description: 'Experience the royal taste of Atreyapuram with our curated All 10 in 1 Signature Pack. Contains a perfect mix of all our special varieties. Handcrafted with pure ghee and love.'
    },
    {
        id: '2',
        name: 'Traditional Dry Fruits Putharekulu',
        category: 'Traditional',
        sweetener: 'Jaggery',
        price: 549,
        originalPrice: 599,
        rating: 4.9,
        reviews: 51,
        image: 'images/p2.jpg',
        badge: 'Best Seller',
        description: 'Our best-selling Traditional Dry Fruits Putharekulu. Loaded with generic dry fruits and jaggery, wrapped in paper-thin rice starch sheets.'
    },
    {
        id: '3',
        name: 'Exotic Special Dry Fruits',
        category: 'Premium Delights',
        sweetener: 'Jaggery',
        price: 749,
        originalPrice: 799,
        rating: 4.7,
        reviews: 13,
        image: 'images/p3.jpg',
        badge: 'Save 6%',
        description: 'For those who want something extra special. Loaded with premium exotic dry fruits like kiwi, figs, and apricots.'
    },
    {
        id: '4',
        name: 'Pure Grated Coconut Putharekulu',
        category: 'Traditional',
        sweetener: 'Jaggery',
        price: 499,
        originalPrice: 549,
        rating: 4.7,
        reviews: 30,
        image: 'images/p1.jpg',
        badge: 'Natural',
        description: 'Filled with fresh grated coconut and jaggery. A village favorite.'
    },
    {
        id: '5',
        name: 'Sugar Free Dry Fruits Box',
        category: 'Dry Fruit Specials',
        sweetener: 'Sugar', /* Using Sugar for sugar-free context or keep Jaggery? Actually let's assume 'Sugar' filter captures artificial/alternative too for now, OR better: distinct. User asked for Bellam/Sugar. Sugar-free is neither? Let's label it 'Sugar' type for simplicity or default Jaggery? Actually, Sugar Free often mimics Sugar taste. Let's put 'Sugar' for anything not Jaggery? Or keep it 'Jaggery' if it's jaggery based but sugar free? The name implies Sugar Free. Let's stick to Jaggery as it's likely the base style. User said "some sugar some bellam". Let's put this as Sugar? No, typically diabetics avoid both. But for this specific filter "Bellam vs Sugar", Sugar Free usually aligns more with the "Modern/Sugar" side or just exclude? Use 'Jaggery' for now as it's a traditional sweet typically. */
        price: 599,
        originalPrice: 649,
        rating: 4.8,
        reviews: 34,
        image: 'images/p5.jpg',
        badge: 'Healthy Choice',
        description: 'Guilt-free indulgence! Our Sugar Free Dry Fruits Box is made with natural sweeteners and loaded with nutrients.'
    },
    {
        id: '6',
        name: 'Family Event Bulk Pack (50 Pcs)',
        category: 'Combo Packs',
        sweetener: 'Jaggery',
        price: 2499,
        originalPrice: 2799,
        rating: 5.0,
        reviews: 8,
        image: 'images/p6.jpg',
        badge: 'Save ₹300',
        description: 'Perfect for family gatherings and events. Get 50 pieces of our finest Putharekulu at a bulk price.'
    },
    {
        id: '7',
        name: 'Chocolate Spread Putharekulu',
        category: 'Chocolate Fusion',
        sweetener: 'Sugar',
        price: 499,
        originalPrice: 549,
        rating: 4.5,
        reviews: 42,
        image: 'images/p5.jpg',
        badge: 'Kids Favorite',
        description: 'A modern twist on a traditional classic! Delicious chocolate spread wrapped in our signature paper-thin layers.'
    },
    {
        id: '8',
        name: 'Cashew & Almond Special',
        category: 'Dry Fruit Specials',
        sweetener: 'Jaggery',
        price: 699,
        originalPrice: 749,
        rating: 4.8,
        reviews: 20,
        image: 'images/p2.jpg',
        badge: 'Premium',
        description: 'Richly loaded with Cashews and Almonds, this is a dry fruit lover\'s dream come true.'
    },
    {
        id: '9',
        name: 'Assorted Mini Putharekulu',
        category: 'Combo Packs',
        sweetener: 'Jaggery',
        price: 349,
        originalPrice: 399,
        rating: 4.6,
        reviews: 28,
        image: 'images/p1.jpg',
        badge: 'New',
        description: 'Bite-sized happiness! A pack of 20 mini Putharekulu in assorted flavors.'
    },
    {
        id: '10',
        name: 'Premium Ghee Roast',
        category: 'Traditional',
        sweetener: 'Jaggery',
        price: 599,
        originalPrice: 649,
        rating: 4.9,
        reviews: 65,
        image: 'images/p2.jpg',
        badge: 'Must Try',
        description: 'Roasted to golden perfection with extra pure ghee. The ultimate traditional experience.'
    },
    {
        id: '11',
        name: 'Dark Chocolate Delight',
        category: 'Chocolate Fusion',
        sweetener: 'Sugar',
        price: 549,
        originalPrice: 599,
        rating: 4.7,
        reviews: 33,
        image: 'images/p5.jpg',
        badge: 'Trending',
        description: 'Rich dark chocolate filling that melts in your mouth. A sophisticated twist.'
    },
    {
        id: '12',
        name: 'Pista & Cashew Roll',
        category: 'Dry Fruit Specials',
        sweetener: 'Jaggery',
        price: 799,
        originalPrice: 849,
        rating: 4.8,
        reviews: 19,
        image: 'images/p3.jpg',
        badge: 'Elite',
        description: 'Loaded generously with pistachios and cashews. A crunchy, nutty delight.'
    },
    {
        id: '13',
        name: 'Diwali Special Gift Box',
        category: 'Combo Packs',
        sweetener: 'Jaggery',
        price: 1499,
        originalPrice: 1699,
        rating: 5.0,
        reviews: 45,
        image: 'images/p4.jpg',
        badge: 'Limited Edition',
        description: 'Beautifully handcrafted gift box containing our top 5 best-selling varieties.'
    },
    {
        id: '14',
        name: 'Jaggery & Sesame Special',
        category: 'Traditional',
        sweetener: 'Jaggery',
        price: 449,
        originalPrice: 499,
        rating: 4.5,
        reviews: 22,
        image: 'images/p1.jpg',
        badge: 'Classic',
        description: 'The authentic taste of sesame and jaggery, a classic combination.'
    },
    {
        id: '15',
        name: 'White Chocolate & Strawberry',
        category: 'Chocolate Fusion',
        sweetener: 'Sugar',
        price: 599,
        originalPrice: 649,
        rating: 4.6,
        reviews: 15,
        image: 'images/p5.jpg',
        badge: 'Unique',
        description: 'Sweet white chocolate paired with tangy strawberry essence.'
    },
    {
        id: '16',
        name: 'Royal Fig & Honey',
        category: 'Premium Delights',
        sweetener: 'Jaggery',
        price: 899,
        originalPrice: 999,
        rating: 4.9,
        reviews: 10,
        image: 'images/p3.jpg',
        badge: 'Exquisite',
        description: 'An exotic blend of figs and pure honey, wrapped in delicacy.'
    },
    {
        id: '17',
        name: 'Family Mega Pack (100 Pcs)',
        category: 'Combo Packs',
        sweetener: 'Jaggery',
        price: 4499,
        originalPrice: 4999,
        rating: 5.0,
        reviews: 5,
        image: 'images/p6.jpg',
        badge: 'Bulk Saver',
        description: 'The ultimate party pack! 100 pieces of assorted Putharekulu for grand celebrations.'
    },
    {
        id: '18',
        name: 'Horlicks & Boost Kids Special',
        category: 'Chocolate Fusion',
        sweetener: 'Sugar',
        price: 499,
        originalPrice: 549,
        rating: 4.7,
        reviews: 50,
        image: 'images/p5.jpg',
        badge: 'Kid Approved',
        description: 'Favorites of every child, now in a crispy Putharekulu form.'
    },
    {
        id: '19',
        name: 'Date Syrup & Walnut',
        category: 'Dry Fruit Specials',
        sweetener: 'Jaggery', /* Date syrup is closer to Jaggery nature than Sugar */
        price: 649,
        originalPrice: 699,
        rating: 4.8,
        reviews: 14,
        image: 'images/p2.jpg',
        badge: 'Healthy',
        description: 'Natural sweetness from dates and crunch from walnuts. No added sugar.'
    },
    {
        id: '20',
        name: 'Wedding Return Gift Hamper',
        category: 'Combo Packs',
        sweetener: 'Jaggery',
        price: 299,
        originalPrice: 349,
        rating: 4.8,
        reviews: 100,
        image: 'images/p4.jpg',
        badge: 'Best Value',
        description: 'Small, elegant hampers perfect for return gifts at weddings and functions.'
    }
];
